import { useMemo } from "react";
import { TableTitleWithTooltip } from "../../components";
import { formatCurrency, getUserTimezone, formatTier } from "../../utils";

export const useRevenueColumn = (props: {
  onViewDetails: (record: any) => void;
}) => {
  const { onViewDetails } = props;

  const columns = useMemo(() => {
    return [
      {
        title: `Distribution time (${getUserTimezone()})`,
        dataIndex: "distributionTime",
        render: (value: string) => value || "--",
      },
      {
        title: (
          <TableTitleWithTooltip
            title="Total revenue share"
            tooltip="Total revenue share earned from your invitees for the day."
          />
        ),
        dataIndex: "totalRevenueShare",
        render: (value: number) =>
          formatCurrency(value, { floor: true, precison: 2 }),
      },
      {
        title: (
          <TableTitleWithTooltip
            title="Total invitee volume"
            tooltip="Total volume generated by your invitees for the day."
          />
        ),
        dataIndex: "totalInviteeVolume",
        render: (value: number) =>
          formatCurrency(value, { floor: true, precison: 2 }),
      },
      {
        title: (
          <TableTitleWithTooltip
            title="My broker tier"
            tooltip="Your latest broker tier for the day. This serves as a reference, as certain tier updates may occur asynchronously under exceptional circumstances."
          />
        ),
        dataIndex: "brokerTier",
        render: (value: string) => formatTier(value),
      },
      {
        title: "Action",
        dataIndex: "action",
        render: (_: any, record: any) => (
          <button
            className="text-purple-light hover:opacity-80 transition-opacity"
            onClick={() => onViewDetails(record)}
          >
            View
          </button>
        ),
      },
    ];
  }, [onViewDetails]);

  return columns;
};
