import { useMemo, ReactNode } from "react";
import { TableTitleWithTooltip } from "../../components";
import { formatCurrency, getUserTimezone, formatTier } from "../../utils";

export interface Column {
  title: ReactNode;
  dataIndex: string;
  render?: (value: any, record: any, index?: number) => ReactNode;
}

export const useRevenueColumn = (props: {
  onViewDetails: (record: any) => void;
  currentPage: number;
}): Column[] => {
  const { onViewDetails, currentPage } = props;

  const columns = useMemo(() => {
    return [
      {
        title: `Distribution time (${getUserTimezone()})`,
        dataIndex: "distributionTime",
        render: (value: string) => value || "--",
      },
      {
        title: (
          <TableTitleWithTooltip
            title="Total revenue share"
            tooltip="Total revenue share earned from your invitees for the day."
          />
        ),
        dataIndex: "totalRevenueShare",
        render: (value: number) =>
          formatCurrency(value, { floor: true, precison: 2 }),
      },
      {
        title: (
          <TableTitleWithTooltip
            title="Total invitee volume"
            tooltip="Total volume generated by your invitees for the day."
          />
        ),
        dataIndex: "totalInviteeVolume",
        render: (value: number) =>
          formatCurrency(value, { floor: true, precison: 2 }),
      },
      {
        title: (
          <TableTitleWithTooltip
            title="My broker tier"
            tooltip="Your latest broker tier for the day. This serves as a reference, as certain tier updates may occur asynchronously under exceptional circumstances."
          />
        ),
        dataIndex: "brokerTier",
        render: (value: string) => formatTier(value),
      },
      {
        title: "Action",
        dataIndex: "action",
        render: (_: any, record: any, index?: number) => {
          // Only the first 7 items on page 1 can be clicked
          const isDisabled =
            currentPage !== 1 || (index !== undefined && index >= 7);

          return (
            <button
              className={
                isDisabled
                  ? "text-base-contrast-36 cursor-not-allowed"
                  : "text-[#9c75ff] hover:text-[#b58fff] transition-colors"
              }
              onClick={() => {
                if (!isDisabled) {
                  onViewDetails(record);
                }
              }}
              disabled={isDisabled}
            >
              View
            </button>
          );
        },
      },
    ] as Column[];
  }, [onViewDetails, currentPage]);

  return columns;
};
