import { GraduationForm } from "../components/GraduationForm";
import { useAuth } from "../context/AuthContext";
import { Card } from "../components/Card";
import WalletConnect from "../components/WalletConnect";

export default function GraduationRoute() {
  const { isAuthenticated, isLoading } = useAuth();

  if (isLoading) {
    return (
      <div className="flex items-center justify-center min-h-[60vh]">
        <div className="i-svg-spinners:three-dots text-4xl text-primary"></div>
      </div>
    );
  }

  return (
    <div className="container mx-auto px-4 py-8">
      <div className="text-center mb-10">
        <h1 className="text-3xl font-bold mb-4">Upgrade Your DEX</h1>
        <p className="text-gray-300 max-w-2xl mx-auto">
          By sending ORDER tokens, you can graduate your DEX to the next tier,
          allowing you to earn fee splits and provide rewards to your traders.
        </p>
      </div>

      {/* Show wallet connect if not authenticated */}
      {!isAuthenticated ? (
        <div className="w-full max-w-3xl mx-auto px-4 py-6 md:py-10">
          <div className="text-center">
            <Card>
              <h2 className="text-lg md:text-xl font-medium mb-3 md:mb-4">
                Authentication Required
              </h2>
              <p className="mb-4 md:mb-6 text-sm md:text-base text-gray-300">
                Please connect your wallet and login to access DEX graduation
                benefits.
              </p>
              <div className="flex justify-center">
                <WalletConnect />
              </div>
            </Card>
          </div>
        </div>
      ) : (
        <>
          <GraduationForm />

          <div className="mt-16 max-w-2xl mx-auto bg-light/5 rounded-xl p-6">
            <h2 className="text-xl font-bold mb-4">Benefits of Graduating</h2>
            <div className="space-y-4">
              <div className="flex gap-4 items-start">
                <div className="bg-primary/20 p-2 rounded-full">
                  <div className="i-mdi:cash-multiple text-primary w-6 h-6"></div>
                </div>
                <div>
                  <h3 className="text-lg font-medium">Fee Revenue</h3>
                  <p className="text-gray-300">
                    Earn a split of trading fees generated by users on your DEX.
                  </p>
                </div>
              </div>

              <div className="flex gap-4 items-start">
                <div className="bg-secondary/20 p-2 rounded-full">
                  <div className="i-mdi:gift text-secondary w-6 h-6"></div>
                </div>
                <div>
                  <h3 className="text-lg font-medium">Trader Rewards</h3>
                  <p className="text-gray-300">
                    Your traders become eligible for ORDER token rewards based
                    on their trading volume.
                  </p>
                </div>
              </div>

              <div className="flex gap-4 items-start">
                <div className="bg-primary/20 p-2 rounded-full">
                  <div className="i-mdi:card-account-details text-primary w-6 h-6"></div>
                </div>
                <div>
                  <h3 className="text-lg font-medium">Unique Broker ID</h3>
                  <p className="text-gray-300">
                    Get your own unique identifier in the Orderly ecosystem to
                    track your revenue and rewards.
                  </p>
                </div>
              </div>
            </div>
          </div>
        </>
      )}
    </div>
  );
}
