export const graduation = {
  "graduation.title": "Graduate Your DEX",
  "graduation.subtitle":
    "By sending ORDER tokens, you can graduate your DEX to earn fee splits and unlock additional features.",
  "graduation.dexSetupRequired.title": "DEX Setup Required",
  "graduation.dexSetupRequired.description":
    "Before you can graduate your DEX to earn trading fees, you need to create a DEX first. Please go to the DEX creation page to set up your own customized decentralized exchange powered by Orderly.",
  "graduation.dexSetupRequired.createDex": "Create Your DEX",
  "graduation.previewRevenue.title": "Preview Revenue Potential",
  "graduation.previewRevenue.description":
    "While you need to create a DEX first, you can still explore the potential revenue you could earn after graduation:",
  "graduation.authRequired.title": "Authentication Required",
  "graduation.authRequired.description":
    "Please connect your wallet and login to access DEX graduation benefits.",
  "graduation.benefits.title": "Benefits of Graduating",
  "graduation.benefits.feeRevenue.title": "Fee Revenue",
  "graduation.benefits.feeRevenue.description":
    "Earn a split of trading fees generated by users on your DEX. Your revenue comes from the custom fee component that you set.",
  "graduation.benefits.uniqueBrokerId.title": "Unique Broker ID",
  "graduation.benefits.uniqueBrokerId.description":
    "Get your own unique identifier in the Orderly ecosystem to track your revenue and rewards. This ID is essential for revenue attribution.",
  "graduation.benefits.builderStaking.title": "Builder Staking Programme",
  "graduation.benefits.builderStaking.description":
    "Access our 5-tier staking system to reduce base fees and unlock additional benefits. Achieve Silver tier (2.75 bps) with 100K ORDER or $30M volume, Gold tier (2.50 bps) with 250K ORDER or $90M volume, Platinum tier (2.00 bps) with 2M ORDER or $1B volume, or Diamond tier (1.00 bps) with 7M ORDER or $10B volume.",
  "graduation.benefits.builderStaking.stakeLink": "Stake ORDER tokens",
  "graduation.benefits.builderStaking.viewDetails": "View programme details",
  "graduation.benefits.builderStaking.sameWalletNote":
    "You must use the same wallet for staking that you used to set up your DEX.",
  "graduation.benefits.enhancedSupport.title": "Enhanced Support & Services",
  "graduation.benefits.enhancedSupport.description":
    "As you progress through higher tiers, unlock additional benefits including dedicated tech support, marketing assistance, and priority for new chain expansions. Platinum and Diamond tier members receive enhanced marketing support, flagship partner program access, and dedicated customer service.",
  "graduation.feeStructure.title": "DEX Fee Structure:",
  "graduation.feeStructure.description":
    "Your custom fees represent the total fees that traders pay. Orderly's base fee (which varies by tier) is deducted from your custom fees to calculate your revenue. The base fee supports the Orderly ecosystem infrastructure and liquidity.",
};
