/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { WoofiWidgetRouter } from "./WoofiWidgetRouter";
export * as factories from "./factories";
export { WoofiWidgetRouter__factory } from "./factories/WoofiWidgetRouter__factory";
