/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace IWOOFiCrossRouterV5 {
  export type SrcInfoStruct = {
    fromToken: AddressLike;
    bridgeToken: AddressLike;
    fromAmount: BigNumberish;
    minBridgeAmount: BigNumberish;
  };

  export type SrcInfoStructOutput = [
    fromToken: string,
    bridgeToken: string,
    fromAmount: bigint,
    minBridgeAmount: bigint
  ] & {
    fromToken: string;
    bridgeToken: string;
    fromAmount: bigint;
    minBridgeAmount: bigint;
  };

  export type DstInfoStruct = {
    eid: BigNumberish;
    bridgeToken: AddressLike;
    toToken: AddressLike;
    minToAmount: BigNumberish;
    airdropNativeAmount: BigNumberish;
    dstGasForCall: BigNumberish;
  };

  export type DstInfoStructOutput = [
    eid: bigint,
    bridgeToken: string,
    toToken: string,
    minToAmount: bigint,
    airdropNativeAmount: bigint,
    dstGasForCall: bigint
  ] & {
    eid: bigint;
    bridgeToken: string;
    toToken: string;
    minToAmount: bigint;
    airdropNativeAmount: bigint;
    dstGasForCall: bigint;
  };

  export type SrcExtSwapInfoStruct = {
    swapRouter: AddressLike;
    data: BytesLike;
  };

  export type SrcExtSwapInfoStructOutput = [
    swapRouter: string,
    data: string
  ] & { swapRouter: string; data: string };

  export type DstExtSwapInfoStruct = {
    swapRouter: AddressLike;
    swapAmount: BigNumberish;
    data: BytesLike;
  };

  export type DstExtSwapInfoStructOutput = [
    swapRouter: string,
    swapAmount: bigint,
    data: string
  ] & { swapRouter: string; swapAmount: bigint; data: string };
}

export declare namespace IWOOFiWidgetRouter {
  export type SwapInfoStruct = {
    fromToken: AddressLike;
    toToken: AddressLike;
    fromAmount: BigNumberish;
    minToAmount: BigNumberish;
    rebateTo: AddressLike;
  };

  export type SwapInfoStructOutput = [
    fromToken: string,
    toToken: string,
    fromAmount: bigint,
    minToAmount: bigint,
    rebateTo: string
  ] & {
    fromToken: string;
    toToken: string;
    fromAmount: bigint;
    minToAmount: bigint;
    rebateTo: string;
  };

  export type ExtSwapInfoStruct = { router: AddressLike; data: BytesLike };

  export type ExtSwapInfoStructOutput = [router: string, data: string] & {
    router: string;
    data: string;
  };
}

export interface WoofiWidgetRouterInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "BASE_FEE_RATE"
      | "BASE_FEE_SHARE_RATE"
      | "ETH_PLACEHOLDER"
      | "brokerFeeRateCap"
      | "brokerFeeRates"
      | "brokerFeeShareRates"
      | "brokerFees"
      | "claimBrokerFee"
      | "claimOwnerFee"
      | "crossSwap"
      | "getBrokerClaimableTokens"
      | "getBrokerClaimableTokensLength"
      | "getOwnerClaimableTokens"
      | "getOwnerClaimableTokensLength"
      | "inCaseTokensGotStuck"
      | "initialize"
      | "isBroker"
      | "owner"
      | "ownerFees"
      | "pause"
      | "paused"
      | "renounceOwnership"
      | "setBroker"
      | "setBrokerFeeRate"
      | "setBrokerFeeRateCap"
      | "setBrokerFeeShareRate"
      | "setWOOFiCrossRouter"
      | "setWOOFiRouter"
      | "swap"
      | "transferOwnership"
      | "unpause"
      | "woofiCrossRouter"
      | "woofiRouter"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BrokerCrossSwap"
      | "BrokerSwap"
      | "Initialized"
      | "OwnershipTransferred"
      | "Paused"
      | "Unpaused"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "BASE_FEE_RATE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "BASE_FEE_SHARE_RATE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ETH_PLACEHOLDER",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "brokerFeeRateCap",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "brokerFeeRates",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "brokerFeeShareRates",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "brokerFees",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "claimBrokerFee",
    values: [AddressLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "claimOwnerFee",
    values: [AddressLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "crossSwap",
    values: [
      AddressLike,
      AddressLike,
      IWOOFiCrossRouterV5.SrcInfoStruct,
      IWOOFiCrossRouterV5.DstInfoStruct,
      IWOOFiCrossRouterV5.SrcExtSwapInfoStruct,
      IWOOFiCrossRouterV5.DstExtSwapInfoStruct
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getBrokerClaimableTokens",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getBrokerClaimableTokensLength",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getOwnerClaimableTokens",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getOwnerClaimableTokensLength",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "inCaseTokensGotStuck",
    values: [AddressLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [AddressLike, AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isBroker",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "ownerFees",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setBroker",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setBrokerFeeRate",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setBrokerFeeRateCap",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setBrokerFeeShareRate",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setWOOFiCrossRouter",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setWOOFiRouter",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "swap",
    values: [
      AddressLike,
      AddressLike,
      IWOOFiWidgetRouter.SwapInfoStruct,
      IWOOFiWidgetRouter.ExtSwapInfoStruct
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "woofiCrossRouter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "woofiRouter",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "BASE_FEE_RATE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "BASE_FEE_SHARE_RATE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ETH_PLACEHOLDER",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "brokerFeeRateCap",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "brokerFeeRates",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "brokerFeeShareRates",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "brokerFees", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "claimBrokerFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimOwnerFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "crossSwap", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getBrokerClaimableTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBrokerClaimableTokensLength",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getOwnerClaimableTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getOwnerClaimableTokensLength",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "inCaseTokensGotStuck",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isBroker", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "ownerFees", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setBroker", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setBrokerFeeRate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setBrokerFeeRateCap",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setBrokerFeeShareRate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setWOOFiCrossRouter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setWOOFiRouter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "swap", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "woofiCrossRouter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "woofiRouter",
    data: BytesLike
  ): Result;
}

export namespace BrokerCrossSwapEvent {
  export type InputTuple = [
    fromToken: AddressLike,
    fromAmount: BigNumberish,
    bridgeToken: AddressLike,
    dstEid: BigNumberish,
    toToken: AddressLike,
    brokerFeeRate: BigNumberish,
    brokerFeeShareRate: BigNumberish
  ];
  export type OutputTuple = [
    fromToken: string,
    fromAmount: bigint,
    bridgeToken: string,
    dstEid: bigint,
    toToken: string,
    brokerFeeRate: bigint,
    brokerFeeShareRate: bigint
  ];
  export interface OutputObject {
    fromToken: string;
    fromAmount: bigint;
    bridgeToken: string;
    dstEid: bigint;
    toToken: string;
    brokerFeeRate: bigint;
    brokerFeeShareRate: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BrokerSwapEvent {
  export type InputTuple = [
    swapType: BigNumberish,
    fromToken: AddressLike,
    fromAmount: BigNumberish,
    toToken: AddressLike,
    toAmount: BigNumberish,
    brokerFeeRate: BigNumberish,
    brokerFeeShareRate: BigNumberish
  ];
  export type OutputTuple = [
    swapType: bigint,
    fromToken: string,
    fromAmount: bigint,
    toToken: string,
    toAmount: bigint,
    brokerFeeRate: bigint,
    brokerFeeShareRate: bigint
  ];
  export interface OutputObject {
    swapType: bigint;
    fromToken: string;
    fromAmount: bigint;
    toToken: string;
    toAmount: bigint;
    brokerFeeRate: bigint;
    brokerFeeShareRate: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InitializedEvent {
  export type InputTuple = [version: BigNumberish];
  export type OutputTuple = [version: bigint];
  export interface OutputObject {
    version: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface WoofiWidgetRouter extends BaseContract {
  connect(runner?: ContractRunner | null): WoofiWidgetRouter;
  waitForDeployment(): Promise<this>;

  interface: WoofiWidgetRouterInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  BASE_FEE_RATE: TypedContractMethod<[], [bigint], "view">;

  BASE_FEE_SHARE_RATE: TypedContractMethod<[], [bigint], "view">;

  ETH_PLACEHOLDER: TypedContractMethod<[], [string], "view">;

  brokerFeeRateCap: TypedContractMethod<[], [bigint], "view">;

  brokerFeeRates: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  brokerFeeShareRates: TypedContractMethod<
    [arg0: AddressLike],
    [bigint],
    "view"
  >;

  brokerFees: TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike],
    [bigint],
    "view"
  >;

  claimBrokerFee: TypedContractMethod<
    [_tokens: AddressLike[]],
    [void],
    "nonpayable"
  >;

  claimOwnerFee: TypedContractMethod<
    [_tokens: AddressLike[]],
    [void],
    "nonpayable"
  >;

  crossSwap: TypedContractMethod<
    [
      to: AddressLike,
      broker: AddressLike,
      srcInfo: IWOOFiCrossRouterV5.SrcInfoStruct,
      dstInfo: IWOOFiCrossRouterV5.DstInfoStruct,
      srcExtSwapInfo: IWOOFiCrossRouterV5.SrcExtSwapInfoStruct,
      dstExtSwapInfo: IWOOFiCrossRouterV5.DstExtSwapInfoStruct
    ],
    [void],
    "payable"
  >;

  getBrokerClaimableTokens: TypedContractMethod<
    [broker: AddressLike, start: BigNumberish, end: BigNumberish],
    [string[]],
    "view"
  >;

  getBrokerClaimableTokensLength: TypedContractMethod<
    [broker: AddressLike],
    [bigint],
    "view"
  >;

  getOwnerClaimableTokens: TypedContractMethod<
    [start: BigNumberish, end: BigNumberish],
    [string[]],
    "view"
  >;

  getOwnerClaimableTokensLength: TypedContractMethod<[], [bigint], "view">;

  inCaseTokensGotStuck: TypedContractMethod<
    [_tokens: AddressLike[]],
    [void],
    "nonpayable"
  >;

  initialize: TypedContractMethod<
    [
      _owner: AddressLike,
      _woofiRouter: AddressLike,
      _woofiCrossRouter: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  isBroker: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  ownerFees: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setBroker: TypedContractMethod<
    [_broker: AddressLike, _flag: boolean],
    [void],
    "nonpayable"
  >;

  setBrokerFeeRate: TypedContractMethod<
    [_brokerFeeRate: BigNumberish],
    [void],
    "nonpayable"
  >;

  setBrokerFeeRateCap: TypedContractMethod<
    [_brokerFeeRateCap: BigNumberish],
    [void],
    "nonpayable"
  >;

  setBrokerFeeShareRate: TypedContractMethod<
    [_broker: AddressLike, _feeShareRate: BigNumberish],
    [void],
    "nonpayable"
  >;

  setWOOFiCrossRouter: TypedContractMethod<
    [_woofiCrossRouter: AddressLike],
    [void],
    "nonpayable"
  >;

  setWOOFiRouter: TypedContractMethod<
    [_woofiRouter: AddressLike],
    [void],
    "nonpayable"
  >;

  swap: TypedContractMethod<
    [
      to: AddressLike,
      broker: AddressLike,
      swapInfo: IWOOFiWidgetRouter.SwapInfoStruct,
      extSwapInfo: IWOOFiWidgetRouter.ExtSwapInfoStruct
    ],
    [bigint],
    "payable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  woofiCrossRouter: TypedContractMethod<[], [string], "view">;

  woofiRouter: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "BASE_FEE_RATE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "BASE_FEE_SHARE_RATE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "ETH_PLACEHOLDER"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "brokerFeeRateCap"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "brokerFeeRates"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "brokerFeeShareRates"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "brokerFees"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "claimBrokerFee"
  ): TypedContractMethod<[_tokens: AddressLike[]], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimOwnerFee"
  ): TypedContractMethod<[_tokens: AddressLike[]], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "crossSwap"
  ): TypedContractMethod<
    [
      to: AddressLike,
      broker: AddressLike,
      srcInfo: IWOOFiCrossRouterV5.SrcInfoStruct,
      dstInfo: IWOOFiCrossRouterV5.DstInfoStruct,
      srcExtSwapInfo: IWOOFiCrossRouterV5.SrcExtSwapInfoStruct,
      dstExtSwapInfo: IWOOFiCrossRouterV5.DstExtSwapInfoStruct
    ],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "getBrokerClaimableTokens"
  ): TypedContractMethod<
    [broker: AddressLike, start: BigNumberish, end: BigNumberish],
    [string[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getBrokerClaimableTokensLength"
  ): TypedContractMethod<[broker: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getOwnerClaimableTokens"
  ): TypedContractMethod<
    [start: BigNumberish, end: BigNumberish],
    [string[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getOwnerClaimableTokensLength"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "inCaseTokensGotStuck"
  ): TypedContractMethod<[_tokens: AddressLike[]], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "initialize"
  ): TypedContractMethod<
    [
      _owner: AddressLike,
      _woofiRouter: AddressLike,
      _woofiCrossRouter: AddressLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "isBroker"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "ownerFees"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setBroker"
  ): TypedContractMethod<
    [_broker: AddressLike, _flag: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setBrokerFeeRate"
  ): TypedContractMethod<[_brokerFeeRate: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setBrokerFeeRateCap"
  ): TypedContractMethod<
    [_brokerFeeRateCap: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setBrokerFeeShareRate"
  ): TypedContractMethod<
    [_broker: AddressLike, _feeShareRate: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setWOOFiCrossRouter"
  ): TypedContractMethod<
    [_woofiCrossRouter: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setWOOFiRouter"
  ): TypedContractMethod<[_woofiRouter: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "swap"
  ): TypedContractMethod<
    [
      to: AddressLike,
      broker: AddressLike,
      swapInfo: IWOOFiWidgetRouter.SwapInfoStruct,
      extSwapInfo: IWOOFiWidgetRouter.ExtSwapInfoStruct
    ],
    [bigint],
    "payable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "woofiCrossRouter"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "woofiRouter"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "BrokerCrossSwap"
  ): TypedContractEvent<
    BrokerCrossSwapEvent.InputTuple,
    BrokerCrossSwapEvent.OutputTuple,
    BrokerCrossSwapEvent.OutputObject
  >;
  getEvent(
    key: "BrokerSwap"
  ): TypedContractEvent<
    BrokerSwapEvent.InputTuple,
    BrokerSwapEvent.OutputTuple,
    BrokerSwapEvent.OutputObject
  >;
  getEvent(
    key: "Initialized"
  ): TypedContractEvent<
    InitializedEvent.InputTuple,
    InitializedEvent.OutputTuple,
    InitializedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;

  filters: {
    "BrokerCrossSwap(address,uint256,address,uint32,address,uint32,uint32)": TypedContractEvent<
      BrokerCrossSwapEvent.InputTuple,
      BrokerCrossSwapEvent.OutputTuple,
      BrokerCrossSwapEvent.OutputObject
    >;
    BrokerCrossSwap: TypedContractEvent<
      BrokerCrossSwapEvent.InputTuple,
      BrokerCrossSwapEvent.OutputTuple,
      BrokerCrossSwapEvent.OutputObject
    >;

    "BrokerSwap(uint8,address,uint256,address,uint256,uint32,uint32)": TypedContractEvent<
      BrokerSwapEvent.InputTuple,
      BrokerSwapEvent.OutputTuple,
      BrokerSwapEvent.OutputObject
    >;
    BrokerSwap: TypedContractEvent<
      BrokerSwapEvent.InputTuple,
      BrokerSwapEvent.OutputTuple,
      BrokerSwapEvent.OutputObject
    >;

    "Initialized(uint64)": TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;
    Initialized: TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
  };
}
